In [4]:
import random
import numpy as np

In [7]:
t1 = np.arange(12).reshape((3, 4)).astype("int8")
print(t1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
print(t1[1, 2])   # 取第二行3列

6


In [10]:
print(t1[:, 1])   # 取t1的第二列

[1 5 9]


In [16]:
print(t1[[0, 2], :])  # 取t1的第1和第3行

[[ 0  1  2  3]
 [ 8  9 10 11]]


#####  三元运算符和裁剪函数

In [19]:
t3 = t1
print(f"t3={t3}")
t3[t3>5] = 5
print(f"t3'={t3}")

t3=[[0 1 2 3]
 [4 5 5 5]
 [5 5 5 5]]
t3'=[[0 1 2 3]
 [4 5 5 5]
 [5 5 5 5]]


In [21]:
print(f"t3={t3}")
print(np.where(t3>4, 400, 100))    # 三元运算符

t3=[[0 1 2 3]
 [4 5 5 5]
 [5 5 5 5]]
[[100 100 100 100]
 [100 400 400 400]
 [400 400 400 400]]


In [23]:
print(t3.clip(4, 6))       # 裁剪函数,小于4的替换为8，大于6的替换为16
                           # 可以用来一个数据大于255的部分替换为255，小于0的替换为0

[[4 4 4 4]
 [4 5 5 5]
 [5 5 5 5]]


##### 注意：我们只能让float类型的矩阵中的元素设置为空值，int类型的会报错

In [30]:
t2 = t1.astype("float")
t2[1:2, 2:3] = np.nan   # 将几个数设置为空值
print(t2)

[[ 0.  1.  2.  3.]
 [ 4.  5. nan  5.]
 [ 5.  5.  5.  5.]]


In [31]:
print(np.isnan(t2))

[[False False False False]
 [False False  True False]
 [False False False False]]


##### 将nan值替换为不会对数组产生影响的值

In [24]:
def fill_ndarray(t):
    for i in range(t.shape[1]):      # 每行中元素的数量
        temp_col = t[:, i]           # 获取当前列的数据内容
        # 函数np.count_nonzero用于统计矩阵中非0值得个数
        # temp_col != temp_col的返回一个矩阵，矩阵中除了空值的位置，其他的位置都是布尔型的0
        nan_num = np.count_nonzero(temp_col != temp_col)
        if nan_num != 0:             # nan_num不为0说明该列数据中有nan值
            temp_no_nan_col = temp_col[temp_col == temp_col]  # 获得当前列不为nan的位置
            # 将nan值得位置附上该列的平均值
            temp_col[temp_col!=temp_col] = temp_no_nan_col.mean()
    return t
print(f"t2={t2}")
print(f"t2'={fill_ndarray(t2)}")

t2=[[ 0.  1.  2.  3.]
 [ 4.  5. nan  7.]
 [ 8.  9. 10. 11.]]
t2'=[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


##### 拼接函数

In [26]:
t4 = t1
t5 = t1
print(t4)

[[0 1 2 3]
 [4 5 5 5]
 [5 5 5 5]]


In [29]:
print(np.hstack((t4, t5)))  # 横向拼接
print(np.vstack((t4, t5)))  # 纵向拼接

[[0 1 2 3 0 1 2 3]
 [4 5 5 5 4 5 5 5]
 [5 5 5 5 5 5 5 5]]
[[0 1 2 3]
 [4 5 5 5]
 [5 5 5 5]
 [0 1 2 3]
 [4 5 5 5]
 [5 5 5 5]]


In [6]:
rgbHist = np.zeros([16 * 16 * 16, 1], np.float32)
print(rgbHist)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
