In [34]:
import numpy as np
import math

In [5]:
# #创建二维数组
data = [[1,2,3],[4,5,6]]
arr = np.array(data)
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
# 创建一个大小为10的空向量
# np.empty 构造一个大小为 shape 的未初始化数组,
# np.zeros 构造一个大小为 shape 的全0数组,
# np.ones 构造一个大小为 shape 的全1数组,
# np.ones 构造一个大小为 shape 的全1数组,
# np.full 构造一个大小为 shape 的用指定值填满的数组,
#
print(np.empty(10))  # 感觉里面的元素是随机生成的。
                     # 所以使用的时候要小心。需要手工把每一个值重新定义，否则该值是一个随机数，调试起来会比较麻烦。
print(np.zeros(10))
print(np.full((2,3),5.0))

[6.23042070e-307 1.42417221e-306 7.56595733e-307 3.33776697e-307
 1.60216183e-306 8.45596650e-307 1.42415456e-306 1.95819945e-306
 1.39178415e+087 8.34420522e-308]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[5. 5. 5.]
 [5. 5. 5.]]


In [9]:
# 查看数组占用内存大小
# hint 每个元素点用内存大小乘以元素个数
sample4_1 = np.empty((2,3), np.uint32)
print(sample4_1.itemsize*sample4_1.size)

24


In [11]:
# hint 使用 np.info函数可以查询函数，类，模块的文档
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [15]:
# 用0-8这9个数构造一个3x3大小的矩阵
np.array(np.arange(9).reshape(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
# 从数组[1,2,0,0,4,0]中找出非0元素的下标
np.nonzero([1,2,3,0,0,1,2,2])

(array([0, 1, 2, 5, 6, 7], dtype=int64),)

In [18]:
print(np.eye(3,3))  #默认第一个和第二个参数相等，第三个参数为对角线位置

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### sample_1就相当于numpy创建出来的对象，所以Numpy中拥有的方法，直接用sample_1.的形式也可以调用类方法

In [22]:
# sample_1就相当于numpy创建出来的对象，所以Numpy中拥有的方法，直接用sample_1.的形式也可以调用类方法
sample_1 = np.random.random((10,10))
print(type(sample_1))
print(sample_1)
# 下面两种调用方法的方式都是可以的，一个是对象调用方法，另一个是调用库中的函数
print(sample_1.max(),sample_1.min())
print(np.max(sample_1),np.min(sample_1))

<class 'numpy.ndarray'>
[[0.02643317 0.37174429 0.45716747 0.91981982 0.98207794 0.48491557
  0.53860001 0.1998808  0.53834438 0.28207999]
 [0.70742453 0.43022133 0.09716766 0.46159149 0.72547122 0.49053557
  0.31194409 0.80107285 0.49262478 0.86663073]
 [0.89440517 0.4243199  0.44371719 0.70617053 0.3901452  0.06272022
  0.01049752 0.12939289 0.73241329 0.2272233 ]
 [0.94804673 0.99866593 0.40923699 0.55834004 0.34145147 0.03358111
  0.63778381 0.13484459 0.64260178 0.07292166]
 [0.14933067 0.39960386 0.50086087 0.83863009 0.4602941  0.96559694
  0.88442252 0.83601666 0.97107352 0.5426123 ]
 [0.15252341 0.88475193 0.58817843 0.78756066 0.51303062 0.99415744
  0.64024246 0.9317302  0.63106858 0.65211171]
 [0.41326134 0.04302947 0.17084661 0.84400127 0.53086767 0.70460029
  0.39251324 0.80557338 0.23887352 0.54871001]
 [0.11907668 0.83905247 0.97110466 0.2342659  0.70467536 0.49943357
  0.84739751 0.8323826  0.86597708 0.40530181]
 [0.81438903 0.72599684 0.81067921 0.50832748 0.53897289

In [23]:
sample_1.mean()

0.5580395946282164

In [26]:
test_1 = np.ones((4,4))
test_1[1:3,1:4] = 0
print(test_1)

[[1. 1. 1. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 1. 1.]]


# t17 感觉没啥用，不如写程序时遇到了再说

In [31]:
# 扩展数组的边界
print(test_1)
# np.pad(test_1, (test_1.shape[0],test_1.shape[1]),mode='constant',constant_values=5)

[[1. 1. 1. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 1. 1.]]


In [35]:

print(0.3 == 3 * 0.1) # False  浮点数可以比大小，但相等要用math.isclose比较
math.isclose(0.3,3*0.1)

False


True